### ISSUE TITLE
Some symbols dont work. Get warning 'Unsupported alternate value.'

### ISSUE THREAD

**Issue by astier** [rmagatti/alternate-toggler#2]
The following symbols don't work to toggle.

```vim
let g:at_custom_alternates = {
    \'+': '-',
    \'<': '>',
    \'==': '!=',
\}
```

If I try I get the message `Unsupported alternate value.`

**Comment by rmagatti** [comment]
Hey @astier so I just tested these custom alts and it works fine.
What didn't work is if I had these symbols inside quotes.

The plugin works with a simple text object manipulation `ciw`, where `w` is a word.
If you try toggling on `==` alone or any of the other symbols it works fine, but if you try it on `'=='` it won't, because the word includes the quotes.

Here's the result of `viw` on a quoted value to better exemplify what I'm saying.

<img width="103" alt="Screen Shot 2021-04-02 at 3 58 48 PM" src="https://user-images.githubusercontent.com/2881382/113457155-5397c980-93cc-11eb-9fd8-e8b0a778231f.png">

**Comment by astier** [comment]
I made the mistake to try to toggle the symbols inside the quote. Indeed without the quotes it works. Thanks.
